### ISSUE TITLE
Lodestar Quickstart Future Roadmap

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar-quickstart#17]
Based on a discussion with Lodestar team members, it was made clearer that:
- `lodestar-quickstart` should not be promoted as an onramp to simplify Ethereum staking UX for Lodestar
- Rather, this repository is a tool for advanced users and/or the Lodestar team to bootstrap a Lodestar node with various EL clients for easier testing, debugging and troubleshooting
- It could be used by operators which seek to have a very typical setup with no-fuss tinkering alongside any of the multiple Ethereum EL clients via Docker
- It is mostly used by Lodestar contributors (but open sourced for advanced users) to easily quickstart a full Ethereum node using Lodestar

Lodestar Quickstart will _not_ seek to implement a full suite of customized features often requested by stakers for stakers upon request. The maintenance of this repository will likely remain very limited and will only prioritize functionality required by the Lodestar team _at our discretion_. Features which aim to customize or extend these scripts are not our priority if it doesn't contribute to our goals defined above. We will likely implement simple, progressive completeness and easy demo of capabilities quickly.

This issue tracks some features that we would like to implement for the scripts in this repository:
- [ ] Add auto-pruning args for EL clients in a typical setup
- [ ] GUI: Simplistic interface for customizing unique configs for each instance (e.g. feeRecipient, jwtToken, flags, etc.)
- [ ] Import/export validator DB #15 
- [ ] Documentation improvements in conjunction with Lodestar docs
- [ ] Web3Signer support
